/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eventhandling;

/**
 *
 * @author Prakash
 */
public class MyForm extends javax.swing.JFrame {

    
    private float TotalClass;
    private float AttendClass;
    private float AttendPercentage;
    private float MinusPercentage;
    private float ClassBunk;
    private String StdName;
    
    /**
     * Creates new form MyForm
     */
    public MyForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        AppLabel = new javax.swing.JLabel();
        NameLbl = new javax.swing.JLabel();
        TotalClassLbl = new javax.swing.JLabel();
        ClassAttendLbl = new javax.swing.JLabel();
        TxtName = new javax.swing.JTextField();
        TxtTotalClass = new javax.swing.JTextField();
        TxtAttendClass = new javax.swing.JTextField();
        BtnSubmit = new javax.swing.JButton();
        BtnReset = new javax.swing.JButton();
        NameDiplayLbl = new javax.swing.JLabel();
        AttendPerLbl = new javax.swing.JLabel();
        BunkResultLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 255, 102));
        setForeground(new java.awt.Color(102, 255, 204));

        AppLabel.setBackground(new java.awt.Color(255, 255, 255));
        AppLabel.setFont(new java.awt.Font("Harlow Solid Italic", 1, 36)); // NOI18N
        AppLabel.setForeground(new java.awt.Color(204, 0, 51));
        AppLabel.setText("Daily Bunk");

        NameLbl.setFont(new java.awt.Font("Monotype Corsiva", 0, 24)); // NOI18N
        NameLbl.setForeground(new java.awt.Color(204, 0, 51));
        NameLbl.setText("Enter Name :");

        TotalClassLbl.setFont(new java.awt.Font("Monotype Corsiva", 0, 24)); // NOI18N
        TotalClassLbl.setForeground(new java.awt.Color(204, 0, 0));
        TotalClassLbl.setText("Total Classes :");

        ClassAttendLbl.setFont(new java.awt.Font("Monotype Corsiva", 0, 24)); // NOI18N
        ClassAttendLbl.setForeground(new java.awt.Color(204, 0, 0));
        ClassAttendLbl.setText("Classes Attend :");

        TxtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNameActionPerformed(evt);
            }
        });

        BtnSubmit.setBackground(new java.awt.Color(51, 204, 0));
        BtnSubmit.setForeground(new java.awt.Color(255, 255, 255));
        BtnSubmit.setText("Submit");
        BtnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSubmitActionPerformed(evt);
            }
        });

        BtnReset.setBackground(new java.awt.Color(255, 0, 0));
        BtnReset.setForeground(new java.awt.Color(255, 255, 255));
        BtnReset.setText("Reset");
        BtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnResetActionPerformed(evt);
            }
        });

        NameDiplayLbl.setFont(new java.awt.Font("Monotype Corsiva", 0, 24)); // NOI18N
        NameDiplayLbl.setForeground(new java.awt.Color(204, 0, 0));

        AttendPerLbl.setFont(new java.awt.Font("Monotype Corsiva", 0, 24)); // NOI18N
        AttendPerLbl.setForeground(new java.awt.Color(255, 0, 51));

        BunkResultLbl.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        BunkResultLbl.setForeground(new java.awt.Color(51, 255, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(AttendPerLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BunkResultLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(BtnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(78, 78, 78)
                                        .addComponent(BtnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(AppLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(NameLbl)
                                                .addComponent(TotalClassLbl)
                                                .addComponent(ClassAttendLbl))
                                            .addGap(73, 73, 73)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(TxtAttendClass, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(TxtName, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(TxtTotalClass, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(22, 22, 22)))))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(NameDiplayLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AppLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameLbl)
                    .addComponent(TxtName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TotalClassLbl)
                    .addComponent(TxtTotalClass, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ClassAttendLbl)
                    .addComponent(TxtAttendClass, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(NameDiplayLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AttendPerLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BunkResultLbl)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void TxtNameActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void BtnResetActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        StdName = "";
        TxtName.setText("");
        TxtAttendClass.setText("");
        TxtTotalClass.setText("");
    }                                        

    private void BtnSubmitActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        StdName = TxtName.getText();
        TotalClass = Float.parseFloat(TxtTotalClass.getText());
        AttendClass = Float.parseFloat(TxtAttendClass.getText());
        
        AttendPercentage = (AttendClass*100)/TotalClass;
        
        if(AttendPercentage >= 85)
        {
            MinusPercentage = (AttendPercentage - 85);
            ClassBunk = (MinusPercentage * TotalClass)/100;
            
        }
        
        NameDiplayLbl.setText("Hey ! "+StdName);
        AttendPerLbl.setText("Your Attendence Percentage is "+AttendPercentage+" %");
        BunkResultLbl.setText("You Can Bunk "+ClassBunk+" Classes");
    }                                         

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel AppLabel;
    private javax.swing.JLabel AttendPerLbl;
    private javax.swing.JButton BtnReset;
    private javax.swing.JButton BtnSubmit;
    private javax.swing.JLabel BunkResultLbl;
    private javax.swing.JLabel ClassAttendLbl;
    private javax.swing.JLabel NameDiplayLbl;
    private javax.swing.JLabel NameLbl;
    private javax.swing.JLabel TotalClassLbl;
    private javax.swing.JTextField TxtAttendClass;
    private javax.swing.JTextField TxtName;
    private javax.swing.JTextField TxtTotalClass;
    // End of variables declaration                   
}
